/// Centralized lists of faculties and departments at Redeemer's University.
///
/// Used in profile creation/editing dropdowns and any other UI that needs
/// these values.
class RunUniversityData {
  RunUniversityData._();

  static const List<String> faculties = [
    'Faculty of Basic Medical Sciences',
    'Faculty of Built Environment Studies',
    'Faculty of Computing and Digital Technology',
    'Faculty of Education',
    'Faculty of Engineering',
    'Faculty of Humanities',
    'Faculty of Law',
    'Faculty of Management Sciences',
    'Faculty of Natural Sciences',
    'Faculty of Social Sciences',
  ];

  static const List<String> departments = [
    'Accounting',
    'Actuarial Science',
    'Applied Biology & Genetics',
    'Architecture',
    'Banking & Finance',
    'Biochemistry',
    'Biological Sciences',
    'Building Technology',
    'Business Administration',
    'Business Education',
    'Christian Religious Studies (CRS)',
    'Civil Engineering',
    'Computer Engineering',
    'Computer Science',
    'Computer Science Education',
    'Cyber Security',
    'Economics',
    'Economics Education',
    'Educational Management',
    'Electrical & Electronics Engineering',
    'English',
    'English Education',
    'Environmental Management & Toxicology',
    'Estate Management',
    'French',
    'Geology',
    'Guidance & Counseling',
    'History & International Studies',
    'Hospitality & Tourism Management',
    'Human Anatomy',
    'Human Physiology',
    'Industrial Chemistry',
    'Industrial Mathematics',
    'Information Technology',
    'Insurance',
    'Law (LL.B)',
    'Marketing',
    'Mass Communication',
    'Mechanical Engineering',
    'Medical Laboratory Science (MLS)',
    'Meteorology',
    'Microbiology',
    'Nursing Science',
    'Philosophy',
    'Physics with Electronics',
    'Physiotherapy',
    'Political Science',
    'Political Science Education',
    'Psychology',
    'Public Administration',
    'Public Health',
    'Quantity Surveying',
    'Religious Studies',
    'Religious Studies Education',
    'Social Work',
    'Sociology',
    'Software Engineering',
    'Statistics',
    'Surveying & Geo‑informatics',
    'Theatre Arts',
    'Tourism Studies',
    'Transport Management',
    'Urban & Regional Planning',
  ];
}
